### ISSUE TITLE
Visualize stitched consensus

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/MiCall#1016]
Users might be confused by how the stitched consensus will be assembled. It would be helpful to display the stitched consensus with the genome map and Blast matches. Maybe include combined coverage? Would it be helpful to add this to the genome coverage map, or would it be less cluttered as a separate diagram?

One example that's confusing is a sample with two contigs: one with a big deletion and the other that covers the deleted region. See POSITION17-HIV-AD_S36 in the 01-Sep-2023.M04401 run.

**Comment by Donaim** [comment]
Our stitching algorithm is currently based on gene regions rather than contigs.
So it is more difficult to visualize it on the existing diagram.

**Comment by Donaim** [comment]
The current stitcher has a visualizer that produces plots similar to our genome coverage maps.
