### ISSUE TITLE
Potential misalignment for run 140415 sample94 causes codon duplication in HIV1B-gag

### ISSUE THREAD

**Issue by tnguyencfe** [cfe-lab/MiCall#209]
![sample94_gag_codonduplication](https://cloud.githubusercontent.com/assets/5864251/7944438/6e9a8a3a-091f-11e5-9d8c-f2ff6b641466.png)

The attached image shows various consensus sequences from run140415-sample94 and indicates that there may be a  misalignment of sequences that hit reference HIV1B-gag.  All the consensus sequences with the names *collated_conseq* are taken from the v6.7 miseqpipeline collated_conseqs.csv file.  The consensus sequence with the name "mycons" is not from the miseqpipeline - it is a consensus of BWA alignments of run 140415-sample94 sequences against HIV1B-gag reference.

The miseqpipeline majority consensus "*HIV1B-gag-seed,15,MAX|collated_conseq.csv*" indicates a 2-codon duplication between (1-based) nucleotide 372 - 384.

According to the "mycons" BWA alignments, the majority consensus of the alignments against the HIV1B-gag reference have a deletion between (1-based) nucleotides 372-377.  There do not appear to be any sequences with duplications in the BWA alignments.  However, there are several sequences where BWA's scoring scheme chose to keep the bases contiguous instead of opening a gap because the read edge was too close to the deletion boundary (372-377).  That is instead of having a read with alignment ...AGGAAA------CC, BWA chose the read alignment ...AGGAAACC, causing part of the read bases to fall into the deletion-positions.

Ask Thuy for her BWA alignments.  They're too big to post to GitHub.

**Comment by donkirkby** [comment]
This problem no longer appears in release 7.6. All the consensus sequences now have the two codon deletion without any duplication.

Closing the issue.
