### ISSUE TITLE
Should we examine mismatch penalty settings in bowtie2?

### ISSUE THREAD

**Issue by ArtPoon** [cfe-lab/MiCall#235]
Eric Enns (visiting scientist) was testing MiCall alongside his pipeline on a plasma-derived sample that contains a large insertion (two codons) in an HXB2-derived _pol_ sequence.  The data were paired FASTQ from a MiSeq run with an amplicon experiment.  The sample population contained two types of insertions in similar locations, one that was shifted 1bp away from the other. 

This test case contains the following variants:

```
r  GAC------AGT
c1 GACGTTCTAAGT
c2  GACAGTTCTAGT
```

`r` is the HXB2 reference sequence.  `c1` occurred in about 21000 reads, and `c2` in about 19000 reads.  `c1` becomes the first consensus sequence after mapping.  The second round of mapping `c2` variants to the `c1`-derived consensus induces a frameshift error because this insertion sequence is essentially a frame shift of the first insertion variant.  This results in the following second consensus sequence:

```
GACGTTCT-AGT
```

because the gap character at position 9 is induced by mapping `c2` reads to the `c1` reference with a insertion of `A` at position 4 and deletion at position 9.

Eric proposes to adjust the Bowtie2 mismatch penalty settings (`--mp`) to lower values.  The default setting allows the mismatch penalty to vary between minimum and maximum values of 2 and 6.  Eric is collapsing this range to (2,2).  This permits more mismatching in mapping variable reads to a given reference.  In this particular case, it permits the second insertion variant to be mapped directly to the `c1` insertion sequence.

MiCall simply returns the HXB2 consensus because both insertions have been clipped out and presumably written to a separate file.  Neither variant exceeds the 50% threshold required to be incorporated into the evolving consensus sequence.  We should confirm whether these insertions are correctly being reported in the insertions file.

**Comment by donkirkby** [comment]
We haven't talked about this in a long time, @ArtPoon. Is there still something here to discuss?

**Comment by ArtPoon** [comment]
No I think this is okay to close!
