### ISSUE TITLE
Excessive numbers of primer sequence getting into data (whole genome HCV)

### ISSUE THREAD

**Issue by ArtPoon** [cfe-lab/MiCall#255]
For example, see run 11-SEP-2015 in NS5b region. There tends to be a spike in coverage up to about 10,000 copies in a reproducible location.  In the mixed-hcv pipeline, we addressed this problem by enforcing a minimum match length.

**Comment by donkirkby** [comment]
Chanson says the primers aren't currently causing us any problems, so I'm going to close this issue. We are already ignoring short reads when choosing an HCV genotype, but we include all reads in the coverage maps, nucleotide frequencies, and amino frequencies.

Feel free to reopen this if it is causing problems.
