### ISSUE TITLE
Merge strand-bias branch into master

### ISSUE THREAD

**Issue by ArtPoon** [cfe-lab/MiCall#257]
Make this part of version 7.1

**Comment by donkirkby** [comment]
The branch never got merged in, @ArtPoon. Should we do that? Is there any documentation for what it does? Any suggestions on how to add tests for the new features?

**Comment by ArtPoon** [comment]
The reason I made this branch was to extract strand-bias statistics so that I could generate reports containing metrics required by Merck.  I wrote it in a hurry and there's still some debugging code in there, e.g., lines 112-115 in `micall/core/aln2counts.py`.

I don't know whether the lab is still interested in having these metrics.  My gut feeling is to discard the branch to minimize disruption to the lab pipeline.

**Comment by donkirkby** [comment]
I'll ask around to see if anyone sees a need for these statistics. Even if we delete the branch, we can still retrieve the feature from commit c66332094f2b37940ef94d6531aed5bfb7323a4e.

**Comment by donkirkby** [comment]
Richard H. says we don't need this feature right now, so I'm deleting the branch and closing the issue.
