### ISSUE TITLE
HCV NS1 and p7 are the same

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/MiCall#278]
The wg1HCV project uses the HCV1A-H77-NS1 coordinate region, but that sequence is identical to the HCV1A-H77-p7 region. Because they are named differently, they are both displayed on the Micall page with identical coverage.

Can we use the same name for both of them? Either NS1 or p7? All the other projects use p7.

**Comment by cbrumme** [comment]
NS1 and p7 are two names for the same thing. I think "p7" is the preferred nomenclature these days.

It would be nice if p7 appeared between E2 and NS2 though, instead of at the end of the list.

**Comment by donkirkby** [comment]
I've added issue #279 to override the sort order.

**Comment by donkirkby** [comment]
Fixed by commit af1c77a5ab3043584f276f4b8cd851b6e20fd6be.
