### ISSUE TITLE
Add new-revision-reprocessing runs to Kive in smaller batches

### ISSUE THREAD

**Issue by rhliang** [cfe-lab/MiCall#288]
Jeff's been having to wait for his jobs to run on Kive because MiCall is in the middle of reprocessing lots of old runs.  I've already created an issue on Kive re: adding priority to Runs (cfe-lab/kive#508), but a workaround for the time being would be for MiCall to add these tasks in smaller batches.  At the moment, MiCall is adding upwards of 100 Runs to the queue at a time, and those Runs are taking up all of the resources.  If MiCall restricted it to, say, 20 at a time, then assuming 4 cores per job, that still leaves a lot of resources to use for newer, higher-priority tasks.

**Comment by donkirkby** [comment]
I added this request to issue #282, because they are closely related. Closing this one as a duplicate.
