### ISSUE TITLE
Large gap in HCV coverage

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/MiCall#302]
On the 02 Feb 2016 run, both versions of the 62201A sample showed a large gap in coverage passing through E1, E2, p7, and NS2. Look at the `remap.csv` data to see if there's a consistent sequence getting soft clipped at the boundaries, then see if we could build a better consensus that would map the whole genome.

Are there other HCV-1 subtypes that would get better coverage?

**Comment by veratai** [comment]
So you know about the "home-grown" probes used on samples labeled with HG.  For these samples, the probes selected for regions in NS5a and NS5b, and maybe NS3 (I can't remember exactly).  These probes were quite effective, so there weren't many sequences obtained outside of these regions of the HCV genome.

But I get the sense that this is something you observed on samples that were not "HG".

-Vera.


On Apr 20, 2016, at 4:02 PM, Don Kirkby wrote:

> On the 02 Feb 2016 run, both versions of the 62201A sample showed a large gap in coverage passing through E1, E2, p7, and NS2. Look at the remap.csv data to see if there's a consistent sequence getting soft clipped at the boundaries, then see if we could build a better consensus that would map the whole genome.
> 
> Are there other HCV-1 subtypes that would get better coverage?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> 

**Please note my new contact information**

Vera Tai, PhD
Bioinformatics Statistician/Research Scientist
BC Centre for Excellence in HIV/AIDS
St. Paul's Hospital
680-1081 Burrard Street
Vancouver, BC V6Z 1Y6
tel: (604) 682-2344 ext 62963
e-mail: vtai@cfenet.ubc.ca

**Comment by donkirkby** [comment]
Thanks, @veratai, I have seen the mound pattern we get from those home-grown probes, but this looks different. It appears in the same sample with both the Illumina probe and the home-grown probes.

**Comment by donkirkby** [comment]
I looked at three of the reads that got soft clipped at the NS2 end of the gap, and then blasted those reads. The soft-clipped part mapped to Core, and all three had the same sequence in the soft-clipped part.

I talked to Chanson and Winnie, and they said it's probably not getting looped in the amplification process,  because it used a random primer process that does fragmentation first.

Chanson looked at several times we analysed the same sample, and they all showed that gap. However, he looked at sample 56730 on Mar 6 2015, Mar 13 2015, and Sep 28 2015, and it showed a similar gap on some, but not all, of those dates.

**Comment by donkirkby** [comment]
I looked at three of the reads that got soft clipped at the E1 end of the gap, and they exactly matched the reads that mapped at the other end of the gap. It looks like the reads map to whichever end of the gap has the longer match, and then soft clip the rest.

**Comment by donkirkby** [comment]
The gap seems to appear in one genotype when it's mixed with another genotype. Perhaps one genotype relies on the other to provide some of its functions?
We found another sample: 73095A-HCV from 15 Jul 2016. This one has a gap from the end of core to the start of p7, contains the first 12 amino acids of p7, then another gap to the middle of NS2. I see individual reads with these three pieces stuck together.

**Comment by donkirkby** [comment]
The D62201-HCV sample from 13 Mar 2015 had the problem described in issue #340, so I processed it on my local workstation and forced it to keep the reference for HCV-1a. When I did that, it reported 1a and 2b with the same gap showing in 1a.

**Comment by donkirkby** [comment]
Here's a list of all the samples for the patient we first discovered the gap in:

* D56730 - 06-Mar-2015
* D56730 - 13-Mar-2015
* D56730 - 28-Sep-2015
* D56966 - 06-Mar-2015
* D56966 - 13-Mar-2015
* D56966 - 21-Oct-2015
* D62201 - 06-Mar-2015
* D62201 - 13-Mar-2015
* D62201 - 26-Feb-2016.M04401
* D62201 - 26-Oct-2015
* D62218 - 02-Nov-2015
* D62218 - 06-Mar-2015
* D62218 - 13-Mar-2015
* D62218 - 26-Feb-2016.M04401
* D62226 - 06-Mar-2015
* D62226 - 06-Nov-2015
* D62226 - 13-Mar-2015
* D62240 - 06-Mar-2015
* D62240 - 13-Mar-2015
* D62240 - 16-Nov-2015

The gap was observed in the two earliest samples. The two earliest samples appear to be GT1a/2 mixed infections. From the third sample on, results seem to indicate an intact GT1a, with lower levels of GT2.

**Comment by donkirkby** [comment]
I'm closing this issue, because the gap seems to be real and not a bug in the software.
