### ISSUE TITLE
Sample with lots of reads didn't map to anything

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/MiCall#320]
In the 160510_M04401 run, sample 78373A-3 had over 100,000 reads, but fewer than 20 mapped to anything. What was in those reads?

Look in the unmapped file to see what's there. These are amplicons, so we should be able to look for the top five most common reads, and blast them.

It's interesting that of the five replicates for 78373A, three mapped fine, and two were almost completely unmapped. See how the top five sequences in the unmapped replicates compare to the top five sequences in the mapped replicates.

**Comment by veratai** [comment]
Let me know and I can run these samples through my checkMiSeq script to see what proportion maps to common contaminants.
-Vera.

**Comment by veratai** [comment]
OK, still don’t know what these unmapped reads are!  I have a script that can check the reads using blast (although it is misbehaving right now).  Maybe can do on a subset so it won’t take forever….unless you’ve already done this.

**Comment by donkirkby** [comment]
I haven't done anything yet, @veratai. Any help is appreciated.

**Comment by veratai** [comment]
For 78373A-3, 90 % of the reads did not hit (with any significance) to anything in GenBank.  Some of the sequences are very repetitive....could just be random junk from the MiSeq.  Suspect that the PCR didn't go well, or PCR product was not added to library making step.

**Comment by donkirkby** [comment]
I just sent a follow-up e-mail to Hope to see if we can close this.

**Comment by donkirkby** [comment]
Hope said:

>The sample mentioned (78373A-3) failed to amplify on a gel, but was run on the MiSeq anyway. This was the same for 78373A-5, which had a similar issue (many reads, none mapping to HCV1a).

I also discussed it with Chanson, and we'll close this for now. If it happens more often, we can try to understand it. It's strange that Vera didn't find any primer sequence.
