### ISSUE TITLE
Evolving consensus didn't evolve enough to be removed

### ISSUE THREAD

**Issue by cbrumme** [cfe-lab/MiCall#342]
Sample 73142A_HCV on the 160722.M01841 is GT1B
Some reads mapped to GT1A, but are clearly GT1B. Due to low coverage (and that only Core and NS4a had contiguous sequence) the reference didn't drift far enough away from GT1A (or close enough to GT1B) to be removed.
There was only 1 round of re-mapping.

**Comment by donkirkby** [comment]
This sample worked fine in version 7.6, probably because of the adapter trimming we added in #312.

Closing this issue.
