### ISSUE TITLE
Download more outputs from mixed-hcv pipeline

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/MiCall#350]
We currently download the `counts.csv` output from the mixed-hcv pipeline, but Anita asked for a couple more outputs to be downloaded. We should also make the file names clearer to distinguish the mixed-hcv outputs from the MiCall outputs.

* [x] Rename `counts` to `mixed_counts`.
* [x] Create an output for `amino_csv` named `mixed_amino`.
* [x] Rename `output_csv` to `mixed_amino_merged`.
* [x] Add these three outputs to the list in `monitor.kive_download.download_results()` and remove `counts`.

**Comment by greenbeard1** [comment]
a batch download button would be good also, so that all the output files from a run can be downloaded at once.

**Comment by donkirkby** [comment]
Batch download has already been requested in the cfe-lab/Kive#511 issue, @greenbeard1.
