### ISSUE TITLE
Have MISEQ_MONITOR recognize already-completed runs

### ISSUE THREAD

**Issue by rhliang** [cfe-lab/MiCall#367]
Just had a Kive crash so I had to cancel all the Runs remaining from the 161014 RunBatch.  When I restarted the monitor, it created a new RunBatch with the same name, and restarted all the runs.  This isn't a huge problem as most of the runs will simply be completely reused, but I was surprised because the monitor does now recognize when things that it wants to run are already pending in the queue.

How easy would it be to make the monitor be able to recognize that a suitable RunBatch already exists and most of the work in it is already done?

**Comment by donkirkby** [comment]
This should be handled by the changes in #343. Don't stop the monitor when the Kive fleet crashes, just cancel any stalled runs. The monitor should restart them all for you.
