### ISSUE TITLE
G2P finds V3LOOP when it's not really there

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/MiCall#395]
For example, 73092A-HCV in the 22 Jul 2016 batch didn't report any HIV in version 7.6, but now reports even coverage of about 1000 for V3LOOP with lots of partial deletions.

Suggested solution: raise the minimum mapping score. Plot all the mapping scores for a couple of HCV samples, plus a couple of V3LOOP samples, and see if there's a good minimum mapping score to use.

**Comment by greenbeard1** [comment]
The HIV/HCV Co-infected samples might be good to look at as well? Just to see how things are doing when both HIV and HCV are in the sample.

**Comment by donkirkby** [comment]
Thanks, @greenbeard1, but I don't think it's relevant to this problem whether the HIV came from coinfection or shared tags. We just want to distinguish HCV reads that just barely mapped to V3LOOP from actual V3LOOP reads.

**Comment by donkirkby** [comment]
Another interesting sample is D56966_HCV from the 21 Oct 2015 batch. It actually lowered the minimum coverage on HCV2-JFH-1-E2 from 114 in v7.6 to 78. This probably happened because it found no V3LOOP in v7.6, but now maps about 3000 reads to V3LOOP.
