### ISSUE TITLE
BaseSpace Micall could allow batch upload of files

### ISSUE THREAD

**Issue by wrpscott** [cfe-lab/MiCall#403]
Rather than starting the Micall pipeline every time, allow the upload of a zip or tarfile for multiple runs at once. 
Related to #346

**Comment by donkirkby** [comment]
The BaseSpace upload either uploads a whole run of samples, or one sample at a time. We don't have any control over that.

Once the samples are uploaded, you can select several of them when starting a MiCall analyis.

Closing this issue, because we don't control the way upload works.
