### ISSUE TITLE
MiCall Reports should have a version number

### ISSUE THREAD

**Issue by wrpscott** [cfe-lab/MiCall#407]
The Resistance reports should have a version number which reflects the software version in a traceable way. Perhaps a commit hash could be used?

**Comment by wrpscott** [comment]
Perhaps something like this would work:
git describe --long --dirty --abbrev=10 --tags
This produces a string of the form 'v7.7.0-4-g5b9322c61c'

**Comment by donkirkby** [comment]
We could probably add something to the script that builds the Docker image to write a version stamp into `version.txt` file, then display the contents in the report.

If the script for building the Docker image is getting more complicated, we should move it from the [contributing] file to a script file in Git.

[contributing]: https://github.com/cfe-lab/MiCall/blob/master/CONTRIBUTING.md#basespace
