### ISSUE TITLE
ProbeFinder  gets stuck on certain sequences

### ISSUE THREAD

**Issue by dmacmillan** [cfe-lab/MiCall#531]
In `/media/macdatafile/Natalie/MiCallDevResultsv7.12.dev23/MiSeq/runs/190809_M01841_0388_000000000-CCKFT/Results/version_7.12/denovo/contigs.csv` row 48. The first 100 nucleotides when aligned to hxb2 gets "stuck" and  `ProbeFinder` seemingly takes forever to return anything. Just wanted to note that here.

**Comment by donkirkby** [comment]
This was caused by having a lot of mixtures in the reference sequence, right? Can we close this issue, @dmacmillan?
