### ISSUE TITLE
Simplify coverage plots

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/MiCall#537]
The detailed view of the coverage plots is very cluttered. One option is described in #422, converting them to SVG and scripting the ability to show and hide some features. Another option is to simplify the static chart.

* [x] Remove V3 overlap, since we now pass V3 reads through the G2P pipeline and the remapping pipeline.
* [x] Move legend outside plot, or hold it separately. (Might be easier in SVG format.)
* [x] Convert deletions, stop codons, partial deletions, and insertions from lines to markers.
* [x] ~~If it's still too busy, consider splitting into separate plots, as shown in [Rougier].~~

[Rougier]: https://doi.org/10.1371/journal.pcbi.1003833.g007

**Comment by CBeelen** [comment]
More ideas:

- [ ] Make the plots wider for longer regions, to prevent all the markers being squished together.
- [ ] The grey bar that indicates key positions (?) could be part of the axes instead of being displayed within the plot.
