### ISSUE TITLE
Add reference sequences for SARS-CoV-2

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/MiCall#549]
Support SARS-CoV-2 samples by adding the [seed reference] and other details.

* [x] Add seed reference.
* [x] Add coordinate references for gene regions, plus key positions if needed.
* [x] Add landmarks for genome coverage map, based on gene regions.
* [x] Handle duplicated base 13468.
* [x] Add `conseq_all.csv` with a minimum coverage of 1, and only `MAX` cutoff.
* [x] Compare consensus sequences with published results for the same samples.
* [x] ~~Handle duplicated base when aligning deletions.~~ Split to #558.

[seed reference]: https://www.ncbi.nlm.nih.gov/nuccore/MN908947

**Comment by ArtPoon** [comment]
I already did this for the BC CDC - want the JSON?

**Comment by donkirkby** [comment]
Thanks, Art. Much appreciated!

**Comment by donkirkby** [comment]
Related conversation at PoonLab/MiCall-Lite#42.

**Comment by rhliang** [comment]
Note to self: look at 

* line 827 of `aln2counts.py` (this is the `get_consensus_rows` method)
* line 373 (where it calls `self.write_consensus`)

**Comment by donkirkby** [comment]
List of samples to [download] and the [toolkit] to download with.

[toolkit]: https://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?view=software
[download]: https://trace.ncbi.nlm.nih.gov/Traces/study/?acc=SRR10903401,SRR10903402,SRR10902284,SRR10948474,SRR10948550,SRR10971381,SRR11092058,SRR11092057,SRR11092056,SRR11092064,SRR11085797,SRR11085737,SRR11085740,SRR11085733,SRR11085736,SRR11085738,SRR11085741,SRR11140744,SRR11140745,SRR11140749,SRR11140748,SRR11140747,SRR11140746,SRR11140751,SRR11140750,SRR11177792,SRR11241254,SRR11241255,SRR11247075,SRR11247076,SRR11247077,SRR11247078,SRR11267811,SRR11278090,SRR11278091,SRR11278092,SRR11278164,SRR11278165,SRR11278166,SRR11278167,SRR11278168,SRR11314339,SRR11267570,SRR11278600,SRR11300652,SRR11313269,SRR11313270,SRR11313271,SRR11313272,SRR11313273,SRR11313274,SRR11313275,SRR11313276,SRR11313277,SRR11313278,SRR11313279,SRR11313280,SRR11313281,SRR11313282,SRR11313283,SRR11313284,SRR11313285,SRR11313286,SRR11313287,SRR11313288,SRR11313289,SRR11313290,SRR11313291,SRR11313292,SRR11313293,SRR11313294,SRR11313295,SRR11313296,SRR11313297,SRR11313298,SRR11313299,SRR11313300,SRR11313301,SRR11313302,SRR11313303,SRR11313304,SRR11313305,SRR11313306,SRR11313307,SRR11313308,SRR11313309,SRR11313310,SRR11313311,SRR11313312,SRR11313313,SRR11313314,SRR11313315,SRR11313316,SRR11313317,SRR11313318,SRR11313319,SRR11313320,SRR11313321,SRR11313322,SRR11313323,SRR11313324,SRR11313325,SRR11313326,SRR11313327,SRR11313328,SRR11313329,SRR11313330,SRR11313331,SRR11313332,SRR11313333,SRR11313334,SRR11313335,SRR11313336,SRR11313337,SRR11313338,SRR11313339,SRR11313340,SRR11313341,SRR11313342,SRR11313343,SRR11313344,SRR11313345,SRR11313346,SRR11313347,SRR11313348,SRR11313349,SRR11313350,SRR11313351,SRR11313352,SRR11313353,SRR11313354,SRR11313355,SRR11313356,SRR11313357,SRR11313358,SRR11313359,SRR11313360,SRR11313361,SRR11313362,SRR11313363,SRR11313364,SRR11313365,SRR11313366,SRR11313367,SRR11313368,SRR11313369,SRR11313370,SRR11313371,SRR11313372,SRR11313373,SRR11313374,SRR11313375,SRR11313376,SRR11313377,SRR11313378,SRR11313379,SRR11313380,SRR11313381,SRR11313382,SRR11313383,SRR11313384,SRR11313385,SRR11313386,SRR11313387,SRR11313388,SRR11313389,SRR11313390,SRR11313391,SRR11313392,SRR11313393,SRR11313394,SRR11313395,SRR11313396,SRR11313397,SRR11313398,SRR11313399,SRR11313400,SRR11313401,SRR11313402,SRR11313403,SRR11313404,SRR11313405,SRR11313406,SRR11313407,SRR11313408,SRR11313409,SRR11313410,SRR11313411,SRR11313412,SRR11313413,SRR11313414,SRR11313415,SRR11313416,SRR11313417,SRR11313418,SRR11313419,SRR11313420,SRR11313421,SRR11313422,SRR11313423,SRR11313424,SRR11313425,SRR11313426,SRR11313427,SRR11313428,SRR11313429,SRR11313430,SRR11313431,SRR11313432,SRR11313433,SRR11313434,SRR11313435,SRR11313436,SRR11313437,SRR11313438,SRR11313439,SRR11313440,SRR11313441,SRR11313442,SRR11313443,SRR11313444,SRR11313445,SRR11313446,SRR11313447,SRR11313448,SRR11313449,SRR11313450,SRR11313451,SRR11313452,SRR11313453,SRR11313454,SRR11313455,SRR11313456,SRR11313457,SRR11313458,SRR11313459,SRR11313460,SRR11313461,SRR11313462,SRR11313463,SRR11313464,SRR11313465,SRR11313466,SRR11313467,SRR11313468,SRR11313469,SRR11313470,SRR11313471,SRR11313472,SRR11313473,SRR11313474,SRR11313475,SRR11313476,SRR11313477,SRR11313478,SRR11313479,SRR11313480,SRR11313481,SRR11313482,SRR11313483,SRR11313484,SRR11313485,SRR11313486,SRR11313487,SRR11313488,SRR11313489,SRR11313490,SRR11313491,SRR11313492,SRR11313493,SRR11313494,SRR11313495,SRR11313496,SRR11313497,SRR11313498,SRR11313499,SRR11313500,SRR11313501,SRR11313502,SRR11313503,SRR11313504,SRR11313505,SRR11313506,SRR11313507,SRR11313508,SRR11313509,SRR11365240,SRR11365239

**Comment by donkirkby** [comment]
Comparing consensus sequences to published results for my first 12 samples:

SRA accession|GISAID accession
--------------------|-------------------------
SRR10903401 |  
SRR10903402 |  
SRR11092056 |  
SRR11092057 |  
SRR11092058 |  
SRR11092064 |  
SRR11140744 |  
SRR11140746 | EPI_ISL_408670
SRR11140748 |  
SRR11140750 |  
SRR11177792 |  
SRR11314339 |

**Comment by ArtPoon** [comment]
You can see our work in progress here (with SRR numbers matched to published accession numbers):
https://github.com/PoonLab/sam2conseq/wiki

I'd be really curious to see what you get!

**Comment by donkirkby** [comment]
Thanks, @ArtPoon, that will save me a bunch of time. I'll let you know what we find.

**Comment by donkirkby** [comment]
Here's a summary of our results compared to the matches identified by @ArtPoon. (How did you find those, Art? Any suggestions on where to find EPI_ISL_408670? It doesn't show up when I search [NCBI].)

[NCBI]: https://www.ncbi.nlm.nih.gov/nuccore/

Run|Compared to|Differences                                                                                                                                                          
---|-----------|-----------                                                                                                                                                          
SRR10903401-SARS_S1|MN988669.1|Very good: 12 mismatches in the first 24 bases under low coverage, and 21 extra A's at the end out of 29881.                                          
SRR10903402-SARS_S2|MN988668.1|Almost perfect: 21 extra A's at the end out of 29881.                                                                                                 
SRR11092056-SARS_S3|MN996530|Bad: 899 mismatches, 17761 missing, and 217 added out of 29854.                                                                                         
SRR11092057-SARS_S4|MN996528.1|Very good: 4 mismatches, 33 missing, and 12 added out of 29891. Missing 14 at the start, a gap of 15 with no coverage at 5397, plus 4 single gaps of no coverage within 20 bases. The mismatches are all in low coverage, 3 are mixtures when coverage is 2. 12 extra A's at the end..                                                    
SRR11092058-SARS_S5|MN996527.1|Bad: lots of sections with no coverage. 38 mismatches, 7606 missing, and 26 added out of 29825.                                                       
SRR11092064-SARS_S6|MN996531.1|Bad: lots of sections with no coverage. 24 mismatches, 4667 missing, and 33 added out of 29857.                                                       
SRR11140744-SARS_S7|EPI_ISL_408670|Failed to fetch comparison sequence.                                                                                                              
SRR11140746-SARS_S8|EPI_ISL_408670|Failed to fetch comparison sequence.                                                                                                              
SRR11140748-SARS_S9|EPI_ISL_408670|Failed to fetch comparison sequence.                                                                                                              
SRR11140750-SARS_S10|EPI_ISL_408670|Failed to fetch comparison sequence.                                                                                                             
SRR11177792-SARS_S11|MT072688|Almost perfect: 57 added out of 29811. A few added to start, most added in tail of A's.                                                                
SRR11314339-SARS_S12|MT192765|Almost perfect: 38 added out of 29829. A few added to start, most added in tail of A's.

**Comment by donkirkby** [comment]
I forgot that I already had EPI_ISL_408670 downloaded. It came from [GISAID]. (Click on Browse, and search by accession id.)

[GISAID]: https://www.epicov.org/epi3/frontend#8c65f

**Comment by ArtPoon** [comment]
I queried the SRR number in the NCBI SRA database to get the sample description and then searched for a similar description in the GISAID annotations.  Not perfect, I know.

**Comment by donkirkby** [comment]
Closing issue, now that basic reporting is working.
