### ISSUE TITLE
Merge separate amplicons for a single sample

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/MiCall#553]
Currently, HCV samples are sequenced and combined from two separate MiSeq samples: a whole-genome sample, and a MIDI sample. The new protocol for SARS-CoV-2 will combine about ten smaller amplicons with overlap. Try to trim the primers, as described in #552, then combine overlapping regions, and report on differences in the overlaps as a QC step. Also think through how this will work for the assembled version.

**Comment by cbrumme** [comment]
Correction to the above: SARS-CoV-2 genomes may be sequenced as ~100 overlapping amplicons (not 10).  These amplicons may be provided in two ways
1. A single set of paired fastq files containing reads from the overlapping amplicons
2. Two sets of paired fastq files. The reads within each set of fastq files would NOT overlap

**Comment by donkirkby** [comment]
In every SARS-CoV-2 run so far, we combined both PCR primer pools into a single "sample" prior to sequencing.  Performance so far has been such that it probably won't be necessary to sequence the two pools separately and make micall combine the two sets of fastqs.

Closing the issue as won't fix.
