### ISSUE TITLE
How to get resistance

### ISSUE THREAD

**Issue by nadine-zakkak** [cfe-lab/MiCall#564]
Hello
I am using Docker to run MiCall and my aim is to find resistance mutations in HIV sequences. 
I tried running the "sample" format of MiCall and I initially thought that the pipeline will find the mutations and create a resistance report, but instead it stopped before finding any resistance mutations (at the cascade_report) as per the Stanford Database. Is there an extra step that I should perform manually to continue the pipeline through the resistance algorithm ?

Thank you!

**Comment by donkirkby** [comment]
Thanks for trying it out, @nadine-zakkak. It looks like there's a bug in the `sample` subcommand. We forgot to call the resistance step.

You can work around it by using the `folder` subcommand for now, and I'll try to push a fix later today.
