### ISSUE TITLE
`seed_group` Missing

### ISSUE THREAD

**Issue by dmacmillan** [cfe-lab/MiCall#597]
A lot of `seed_group`s are `null` in `micall/projects.json`. These must be set to something in order for them to be loaded into QAI.

**Comment by donkirkby** [comment]
The seed groups only need to be set on seed regions, not on coordinate regions. I filtered out all the amino acid sequences and looked for ones that had no seed group. Those ones are the newly added regions that don't translate to amino acids.
I think all the regions that need a seed group have one, so I'm closing this issue.
