### ISSUE TITLE
Possible to output micall version #?

### ISSUE THREAD

**Issue by HopeLapointe** [cfe-lab/MiCall#627]
Would be great to have one of the following added to the pipeline for tracking pipeline versions:
1) A text file output (e.g. "micall_version") containing the micall version # being used to process the data
2) rename the default "micall-results" output folder to "micall-results_vX.Y"

Having both options may be a good idea as well.

**Comment by donkirkby** [comment]
Good suggestion, Hope. The docker image does contain a text file with the version number in it, but it's currently only included in the resistance reports. Using it as a default for the output folder makes sense. I'll think about where else I can put it.

**Comment by HopeLapointe** [comment]
Thanks Don! Note that I just checked the resistance reports on one of my samples, and it says "MiCall v0-dev" rather than "MiCall v7.14.dev0" which is the docker version I ran.

Having the version # somewhere else as well will also be good for non HIV/HCV runs (e.g. COVID, which don't output the resistance reports). I do like having them in the reports as well though.

![image](https://user-images.githubusercontent.com/33923896/96516514-2b505000-121c-11eb-8541-9af5517e7599.png)

**Comment by donkirkby** [comment]
If you want to get the proper version in those files, you have to build the docker image with the `docker_build.py` script. I didn't walk you through those details, because I was trying to keep it simple. When I publish the docker image on dockerhub, it will contain the version number. I'll try to make that version number more visible in the 7.14 release, as you suggested.

**Comment by donkirkby** [comment]
@HopeLapointe, I just published the new version on Docker Hub, so you should be able to run it like this to pull the new version:

    sudo docker run --rm cfelab/micall:v7.13.6 --help

That includes the proper version in the report files.
