### ISSUE TITLE
KeyError in update_qai.py

### ISSUE THREAD

**Issue by CBeelen** [cfe-lab/MiCall#792]
I'm getting a `KeyError` when running `micall_watcher.py` in `update_qai.py`. This is the traceback:
```
Traceback (most recent call last):
  File "/home/charlotte/Documents/Git/MiCall/micall/monitor/update_qai.py", line 404, in process_folder
    process_remapped(result_folder, session, run, pipeline_version)
  File "/home/charlotte/Documents/Git/MiCall/micall/monitor/update_qai.py", line 427, in process_remapped
    upload_review_to_qai(f, f2, f3, run, sample_sheet, conseqs, session,
  File "/home/charlotte/Documents/Git/MiCall/micall/monitor/update_qai.py", line 282, in upload_review_to_qai
    decisions = build_review_decisions(coverage_file, collated_counts_file,
  File "/home/charlotte/Documents/Git/MiCall/micall/monitor/update_qai.py", line 210, in build_review_decisions
    project_region_id = project_region_map[(coverage['project'],
KeyError: ('NFLHIVDNA', 'HIV1B-tat')
```
NFLHIVDNA does in fact not have a tat region in `projects.json`.

Suggested solution:
* [x] ~~Use `get()` instead of `__getitem__()`, and skip over regions that aren't in the project.~~
* [x] Compare other project codes with HIV, and check with @cbrumme whether the other full-genome projects should include all the regions we just added to HIV.
* [x] Add missing regions to NFLHIVDNA

**Comment by donkirkby** [comment]
That's weird. Can you check what other differences there are between the various flavours of HIV project?
I'm pretty sure there's a microtest sample that uses the PR-RT project or some other subset of HIV. I wonder the error only occurs when you get reads in a region that the project code doesn't include.

Suggested solution:
* [ ] Use `get()` instead of `__getitem__()`, and skip over regions that aren't in the project.
* [ ] Compare other project codes with HIV, and check with @cbrumme whether the other full-genome projects should include all the regions we just added to HIV.

**Comment by donkirkby** [comment]
I moved the checklist into the first comment, so they show up as tasks.

**Comment by CBeelen** [comment]
I checked out the other full-length projects we have for HIV (HIV, HIVGHA, and HIVB), and they all have the same set of regions. I'll check with Chanson about NFLHIVDNA!

**Comment by CBeelen** [comment]
Chanson says that we only have the different project codes to allow for different coverage/analysis/output requirements, and that the regions should all be the same. So I'll copy over the information from HIV for NFLHIVDNA for now! In the long run, we could think about whether we want to use one template for all HIV flavours, so we don't need to modify each project each time we change regions.

**Comment by CBeelen** [comment]
Aha! I just noticed that NFLHIVDNA does have tat in `project_scoring.json`, but HIV, and therefore also HIVGHA and HIVB, do not. Maybe that was what was causing the error. We probably want to add tat for all HIV projects in `project_scoring.json` as well, to be consistent.

**Comment by donkirkby** [comment]
Agreed.
