### ISSUE TITLE
Update minimap2 to the newest version

### ISSUE THREAD

**Issue by CBeelen** [cfe-lab/MiCall#840]
When testing the new release's results for 7.15, we initially started testing with minimap2 version 2.24. However, there were a couple of samples with a big deletion in HCV spanning E1 and E2. In the previous release, minimap2 version 2.17 had (correctly) aligned the part before the deletion to Core. Minimap 2.24 was not able to do this and only aligned the part after the deletion to the reference. This happened for the denovo version only.
Further checks: the concordance of the part before the deletion to Core is high, and when we tried only aligning the part before the deletion to the reference, it did map to Core in version 2.24 as well. Gotoh produces the same alignment as minimap2 version 2.17.
The samples where this happened were:
D62201-HCV_S26 from run 150306_M01841
D56730-HCV_S12 from run 150313_M01841
D62201-HCV_S26 from run 150313_M01841
73060A-HCV_S46 from run 160715_M01841
73095A-HCV_S3 from run 160715_M01841

Update minimap2 to the newest version, and see if there is a way to fix the alignment for these samples. So far, we have always been using the `map-ont` preset for the alignment.

**Comment by CBeelen** [comment]
I have now also added a unit test that reproduces the alignment issue, [here.](https://github.com/cfe-lab/MiCall/blob/5b5bdc2865cf77a089ca7e4ef16ee100c08726a2/micall/tests/test_consensus_aligner.py#L411)

**Comment by Donaim** [comment]
Done in https://github.com/cfe-lab/MiCall/pull/1027
