### ISSUE TITLE
Update HIVdb to 9.4

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/MiCall#884]
We currently use 9.0. The 9.2 [release] only has comment changes, not score changes, but 9.1 does have score changes.

[release]: https://hivdb.stanford.edu/page/algorithm-updates/

**Comment by CBeelen** [comment]
[HIVdb 9.3](https://hivdb.stanford.edu/page/algorithm-updates/#version.9.3.update.2022-11-20) was released on November 20th, and it includes score changes as well, as per their announcement:

> This version includes important score updates for NRTI drugs ABC, AZT, TDF, and 3TC/FTC.
