### ISSUE TITLE
Update to Python 3.11

### ISSUE THREAD

**Issue by CBeelen** [cfe-lab/MiCall#981]
It would be nice to update to a newer Python version, because the most recent numpy and scipy updates do not support Python 3.8 anymore.
However, we're being held back by minimap2: our current version 2.17 does not work with Python 3.11, but all newer versions (most recent is 2.26) have an alignment idiosyncrasy that we don't like. I've added a new unit test to demonstrate the issue [here.](https://github.com/cfe-lab/MiCall/blob/5b5bdc2865cf77a089ca7e4ef16ee100c08726a2/micall/tests/test_consensus_aligner.py#L411) The problem is also documented in more detail in #840, with a list of (some of the) affected samples.

**Comment by Donaim** [comment]
Done in https://github.com/cfe-lab/MiCall/pull/1167
