### ISSUE TITLE
Add HIV-AD project code

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/MiCall#998]
We're planning a new research project that will be similar to the HIV-GHA project code. The plan is to clone the HIV-GHA project code, then make small changes to it:

* [ ] Clone the project in MiCall and change the name to HIV-AD.
* [ ] Clone the project code in QAI database.
* [x] Change the list of PCR primers in `micall/data/primers_*.fasta`
* [ ] Use the same list of references, including the extras that HIV-GHA uses?

**Comment by Donaim** [comment]
I think this is done

**Comment by Donaim** [comment]
Closed by https://github.com/cfe-lab/MiCall/pull/1013
